name: My Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      run: docker build . -t azmiqa1/testing-image:latest
    - name: push
      run: |
        docker login -u azmiqa1 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push azmiqa1/testing-image:latest
